build:
  nodes:
    coverage:
      tests:
        override:
          - command: php ./script/test_with_coverage.php
            coverage:
              file: tests/report/clover.xml
              format: clover
    analysis:
      resources:
        cpus: 4
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - src/
  excluded_paths:
    - src/base.php
    - src/collection.php
    - src/error.php
    - src/errors.php
    - src/exception.php
    - src/resource.php
    - src/response.php
