name: test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Setup Composer
        uses: ramsey/composer-install@v4
        with:
            composer-options: "--no-scripts"

      - name: Run phpunit
        run: ./vendor/bin/phpunit
