name: test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5']
        dependency-versions: ['lowest', 'highest']
    name: Test (php ${{ matrix.php-version }}, composer ${{ matrix.dependency-versions }})
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Setup Composer
        uses: ramsey/composer-install@v4
        with:
          composer-options: "--no-scripts"
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Run phpunit
        run: ./vendor/bin/phpunit
